# baseURL should be
# "https://YOUR-GITHUB-USERNAME.github.io/lean-site-template/" during development,
# and "your-ea-domain.org/" after your domain has been set up.
baseURL = "https://ea-usyd.github.io/lean-site-template/"
theme = "local-ea-template"
canonifyURLs = true

# If you are using multiple languages and want a different default,
# you can change this language code. In this particular case,
# baseURL will be the English site, and baseURL/<language code> will be the
# other languages.
DefaultContentLanguage = "en"

# These params are used by the local EA Hugo template
# used to generate the site. You can find the template
# at https://github.com/rtcharity/local-ea-template.
  [params]

  [Languages]
  [Languages.en]
  title = "Effective Altruism USYD"
  weight = 1
  languageCode = "en"

  [Languages.en.general]
  ## -- GENERAL SITE PARAMETERS -- ##
  fullTitle = "Effective Altruism at the University of Sydney"
  strapline = "A Life of Positive Impact"

  [Languages.en.groupinfo]
  ## -- EA GROUP INFO -- ##
  legalOrgName = "Effective Altruism USYD"
  orgLocations = "Sydney"
  contactEmail = "eausyd@gmail.com"

  [Languages.en.navbar]
  ## -- NAVIGATION BAR HEADERS -- ##
  # You probably don't need/want to change these,
  # but if you do you'll also want to change the relevant .md file under the
  # content folder so the copy corresponds with the header.
  home = "Home"
  faq = "FAQ"
  effectiveAltruism = "Effective Altruism"
  aboutEA = "About EA"
  readingMaterial = "Reading Material"
  keyTerms = "Key Terms"
  organizations = "Related Organisations"
  contact= "Contact"

  [Languages.en.pages]
  ## -- PAGE HEADERS -- ##
  contactPageHeader = "Contact us"
  aboutEAPageHeader = "What is Effective Altruism?"

  [Languages.en.homepage]
   ## -- HOMEPAGE -- ##
  topBannerText = "Who are we?"
  leadText = "We're a group of people who examine the question: how can I have a positive impact with my life and career?"
  firstSectionHeader = "Doing good better"
  secondSectionHeader = "Building a community"
  thirdSectionHeader = "Finding better ways to make a difference"
  bottomBannerText = "A proud member of the effective altruism network"

  [Languages.en.contactform]
  ## -- CONTACT FORM -- ##
  leadText = "Get in touch!"
  senderName = "Your name (required)"
  senderEmail = "Your email (required)"
  emailSubject = "Subject"
  emailMessage = "Your Message"
  send = "Send"

  [Languages.en.jumbotron]
  # These are the buttons right under the header that appears on the main page.
  # You can use them to link to a mailing list or Facebook page.
  # Make sure the links start with http:// or https://
  firstButtonText = "Join our Mailing List"
  firstButtonLink = "https://docs.google.com/forms/d/e/1FAIpQLSdQb4hRN1nJ6xByzUVTrGLqdfrWSq2bmCVisk-dDwZnCJ09wQ/viewform"
  secondButtonText = "Like us on Facebook"
  secondButtonLink = "https://www.facebook.com/EAUSYD/"
  # Remove the # before the text to add the optional Meetup button
  # meetupButtonText = "Find us on Meetup"

  [Languages.en.urls]
  ## -- EA GROUP FB/TWITTER/MEETUP URLS -- ##
  # If your group does not have URLs for these, just add # before the line
  # to remove the link from the site
  facebookUrl = "https://www.facebook.com/EAUSYD/"
  # twitterUrl = ""
  # meetupUrl = ""
